# -*- coding: utf-8 -*-
"""SIP_Advisior.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZsI6VU6Ul5Ppmwg5KZhn_bHDFqWv31hQ
"""

import streamlit as st
import pandas as pd
import requests
import numpy as np
import datetime
from transformers import pipeline

# Hugging Face model for recommendation
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# SIP return calculator
def calculate_sip_return(amount, years, rate):
    months = years * 12
    monthly_rate = rate / 100 / 12
    future_value = amount * (((1 + monthly_rate)**months - 1) / monthly_rate) * (1 + monthly_rate)
    return round(future_value, 2)

# Load Mutual Fund Data (free API or static CSV if no API available)
def load_mf_data():
    url = "https://api.mfapi.in/mf"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return response.json()
        else:
            return []
    except:
        return []

def get_fund_name_by_category(data, category):
    return [d for d in data if category.lower() in d['schemeName'].lower()]

# AI Recommendation
def get_recommendation(fund_summary):
    labels = ["Buy", "Hold", "Sell"]
    result = classifier(fund_summary, labels)
    return result['labels'][0]

# Chatbot FAQ logic
def chatbot_response(query):
    faqs = {
        "what is sip": "SIP stands for Systematic Investment Plan. It's a way to invest in mutual funds regularly.",
        "types of sip": "Types include Regular SIP, Step-up SIP, Flexi SIP, Perpetual SIP, etc.",
        "benefits": "SIP helps inculcate financial discipline, rupee cost averaging and long term wealth creation.",
        "how to start": "You can start by selecting a mutual fund scheme and setting up an auto-debit instruction.",
        "calculate return": "Use the SIP calculator below to estimate future returns based on your inputs."
    }
    query = query.lower()
    for key in faqs:
        if key in query:
            return faqs[key]
    return "I can help with SIP basics, benefits, types, and return calculations. Try asking: 'What is SIP?'"

# Streamlit UI
st.set_page_config(page_title="SIP Advisor", layout="centered")
st.title("\U0001F4B8 SIP (Mutual Fund) Investment Advisor")

menu = st.sidebar.selectbox("Choose Option", ["Search SIPs", "SIP Calculator", "SIP Chatbot"])

data = load_mf_data()

if menu == "Search SIPs":
    search_type = st.radio("Search by:", ["AMC", "Category"])
    keyword = st.text_input("Enter AMC or Category keyword")

    if keyword:
        results = get_fund_name_by_category(data, keyword)
        if results:
            selected = st.selectbox("Select a scheme:", [r['schemeName'] for r in results])
            scheme = next((r for r in results if r['schemeName'] == selected), None)
            if scheme:
                st.write(f"**Scheme Code:** {scheme['schemeCode']}")
                st.write(f"**Scheme Name:** {scheme['schemeName']}")
                recommendation = get_recommendation(scheme['schemeName'])
                st.success(f"AI Recommendation: {recommendation}")
        else:
            st.warning("No schemes found for this keyword.")

elif menu == "SIP Calculator":
    st.subheader("\U0001F4C8 Calculate Your SIP Returns")
    monthly_invest = st.number_input("Monthly Investment Amount (₹)", min_value=500, value=2000, step=100)
    years = st.slider("Investment Duration (Years)", 1, 30, 5)
    expected_return = st.slider("Expected Annual Return (%)", 5.0, 20.0, 12.0)

    if st.button("Calculate"):
        result = calculate_sip_return(monthly_invest, years, expected_return)
        st.success(f"Estimated Future Value: ₹{result:,}")

elif menu == "SIP Chatbot":
    st.subheader("\U0001F916 Ask About SIPs")
    query = st.text_input("Ask me anything about SIP (e.g., What is SIP?)")
    if query:
        answer = chatbot_response(query)
        st.info(answer)

st.markdown("---")
st.markdown("Built with ❤️ using open-source tools")